# -*- coding: utf-8 -*-
"""cube.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lq3QqJTLQiaEMl17Ji8IVhjVD59gfYnq
"""

list=[2,4,6,8,10]
for i in list:
    print(i**2)
    print(i**3)

